/*
 *
 * Task code generated by SAS Studio 4.2 
 *
 * Generated on '5/17/17, 2:58 PM' 
 * Generated by 'scnfuc' 
 * Generated on server 'RDCESX04106.' 
 * Generated on SAS platform 'Linux LIN X64 4.1.12-61.1.22.el7uek.x86_64' 
 * Generated on SAS version 'V.03.02M0P03082017' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' 
 * Generated on web client 'http://rdcesx15214.race.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B08%253A00' 
 *
 */

/*--Set output size--*/
ods graphics / reset imagemap;

/*--SGPLOT proc statement--*/
proc sgplot data=MYCAS.CRIMECENSUS;
	/*--TITLE and FOOTNOTE--*/
	title "Types of Crimes and Arrest Rates";

	/*--Bar chart settings--*/
	vbar fbi_code / categoryorder=respdesc group=Arrest groupdisplay=Stack name='Bar';

	/*--Category Axis--*/
	xaxis display=(nolabel);

	/*--Response Axis--*/
	yaxis;
run;

ods graphics / reset;
title;